import "server-only";

import { z } from "zod";
import { throw_error } from "@/features/inventory_management_system/shared/error-codes";
import { WishlistRepository } from "../repositories/wishlist.repository";
import { WishlistItemRepository } from "../repositories/wishlist_item.repository";
import { WishlistAnalyticsRepository } from "../repositories/analytics.repository";
import { WishlistCacheService } from "./wishlist-cache.service";
import { WISHLIST_CACHE_KEYS } from "../constants/cache-keys";
import type { wishlist_analytics_query_dto } from "../models/analytics.dto";
import type { WishlistAnalyticsSummary, WishlistEventType } from "../types";

export class WishlistAnalyticsService {
  constructor(
    private readonly wishlist_repo = new WishlistRepository(),
    private readonly item_repo = new WishlistItemRepository(),
    private readonly event_repo = new WishlistAnalyticsRepository(),
    private readonly cache = new WishlistCacheService(),
  ) {}

  async record_event(
    customer_id: string | null,
    wishlist_id: string | null,
    product_id: string | null,
    event_type: WishlistEventType,
    metadata?: Record<string, unknown>,
  ) {
    try {
      await this.event_repo.record_event({
        id: undefined as any, // auto-generated by defaultFn
        customer_id,
        wishlist_id,
        product_id,
        event_type,
        metadata: metadata ?? {},
      });
    } catch {
      // Non-critical analytics, swallow errors
    }
  }

  async get_summary(input: z.infer<typeof wishlist_analytics_query_dto>): Promise<WishlistAnalyticsSummary> {
    const cache_key = WISHLIST_CACHE_KEYS.analytics.summary();
    const cached = await this.cache.get<WishlistAnalyticsSummary>(cache_key);
    if (cached) return cached;

    const period_days = input.period === "7d" ? 7 : input.period === "30d" ? 30 : input.period === "90d" ? 90 : 365;
    const since = new Date(Date.now() - period_days * 86400000).toISOString();

    const [
      total_wishlists,
      active_wishlists,
      total_saved_products,
      total_adds,
      total_conversions,
      purchased_count,
      growth_data,
      conversion_trends,
      most_wished_raw,
    ] = await Promise.all([
      this.wishlist_repo.get_total_wishlists(),
      this.wishlist_repo.get_active_wishlists_count(since),
      this.item_repo.get_total_saved_products(),
      this.event_repo.get_total_adds(since),
      this.event_repo.get_total_conversions(since),
      this.item_repo.get_purchased_count(),
      this.event_repo.get_growth_data(period_days),
      this.event_repo.get_conversion_trends(period_days),
      this.event_repo.get_most_wished_products(10, period_days),
    ]);

    const wishlist_conversion_rate = total_adds > 0
      ? Math.round((total_conversions / total_adds) * 10000) / 100
      : 0;

    const summary: WishlistAnalyticsSummary = {
      total_wishlists,
      active_wishlists,
      total_saved_products,
      wishlist_conversion_rate,
      revenue_from_wishlists: 0, // Would join with orders
      wishlist_growth: growth_data,
      conversion_trends,
      most_wished_products: most_wished_raw.map((m) => ({
        product_id: m.product_id,
        name: m.product_id,
        count: m.count,
      })),
      most_wished_brands: [],
      most_wished_categories: [],
    };

    await this.cache.set(cache_key, summary, WISHLIST_CACHE_KEYS.analytics.ttl);
    return summary;
  }

  async get_product_stats(product_id: string) {
    const [wishlist_count, favorite_count] = await Promise.all([
      this.event_repo.get_event_count_by_type("add_to_wishlist"),
      this.event_repo.get_event_count_by_type("favorite_product"),
    ]);

    return {
      wishlist_count,
      favorite_count,
      wishlist_conversions: 0,
    };
  }

  async get_trending_wishlist_products(limit = 20, period_days = 7) {
    const since = new Date(Date.now() - period_days * 86400000).toISOString();
    const events = await this.event_repo.get_events_by_type_since("add_to_wishlist", since);

    const product_counts = new Map<string, number>();
    for (const event of events) {
      if (event.product_id) {
        product_counts.set(event.product_id, (product_counts.get(event.product_id) ?? 0) + 1);
      }
    }

    return Array.from(product_counts.entries())
      .sort((a, b) => b[1] - a[1])
      .slice(0, limit)
      .map(([product_id, count]) => ({ product_id, count }));
  }

  async get_abandoned_products(limit = 10) {
    const period_days = 30;
    const since = new Date(Date.now() - period_days * 86400000).toISOString();
    const adds = await this.event_repo.get_events_by_type_since("add_to_wishlist", since);
    const conversions = await this.event_repo.get_events_by_type_since("purchase_from_wishlist", since);

    const added_products = new Set(adds.filter((e) => e.product_id).map((e) => e.product_id));
    const converted_products = new Set(conversions.filter((e) => e.product_id).map((e) => e.product_id));

    const abandoned = [...added_products].filter((id) => id && !converted_products.has(id)).slice(0, limit);

    return abandoned.map((product_id) => ({
      product_id: product_id!,
      adds: adds.filter((e) => e.product_id === product_id).length,
    }));
  }

  async get_high_converting_products(limit = 10) {
    const period_days = 90;
    const since = new Date(Date.now() - period_days * 86400000).toISOString();
    const adds = await this.event_repo.get_events_by_type_since("add_to_wishlist", since);
    const conversions = await this.event_repo.get_events_by_type_since("purchase_from_wishlist", since);

    const add_counts = new Map<string, number>();
    for (const event of adds) {
      if (event.product_id) add_counts.set(event.product_id, (add_counts.get(event.product_id) ?? 0) + 1);
    }
    const conversion_counts = new Map<string, number>();
    for (const event of conversions) {
      if (event.product_id) conversion_counts.set(event.product_id, (conversion_counts.get(event.product_id) ?? 0) + 1);
    }

    const products = [...new Set([...add_counts.keys(), ...conversion_counts.keys()])]
      .map((pid) => ({
        product_id: pid,
        adds: add_counts.get(pid) ?? 0,
        conversions: conversion_counts.get(pid) ?? 0,
        rate: (add_counts.get(pid) ?? 0) > 0
          ? Math.round(((conversion_counts.get(pid) ?? 0) / (add_counts.get(pid) ?? 1)) * 10000) / 100
          : 0,
      }))
      .filter((p) => p.adds > 0)
      .sort((a, b) => b.rate - a.rate)
      .slice(0, limit);

    return products;
  }

  async invalidate_cache() {
    await this.cache.invalidate_analytics();
  }
}

export const wishlist_analytics_service = new WishlistAnalyticsService();
