ALTER TABLE `invoices` ADD `deleted_at` timestamp;--> statement-breakpoint
ALTER TABLE `invoices` ADD `deleted_by` varchar(255);--> statement-breakpoint
ALTER TABLE `invoices` ADD `restored_at` timestamp;--> statement-breakpoint
ALTER TABLE `invoices` ADD `restored_by` varchar(255);--> statement-breakpoint
ALTER TABLE `campaigns` ADD `deleted_at` timestamp;--> statement-breakpoint
ALTER TABLE `campaigns` ADD `deleted_by` varchar(255);--> statement-breakpoint
ALTER TABLE `campaigns` ADD `restored_at` timestamp;--> statement-breakpoint
ALTER TABLE `campaigns` ADD `restored_by` varchar(255);--> statement-breakpoint
ALTER TABLE `feature_flags` ADD `deleted_at` timestamp;--> statement-breakpoint
ALTER TABLE `feature_flags` ADD `deleted_by` varchar(255);--> statement-breakpoint
ALTER TABLE `feature_flags` ADD `restored_at` timestamp;--> statement-breakpoint
ALTER TABLE `feature_flags` ADD `restored_by` varchar(255);--> statement-breakpoint
ALTER TABLE `warehouses` ADD `deleted_at` timestamp;--> statement-breakpoint
ALTER TABLE `warehouses` ADD `deleted_by` varchar(255);--> statement-breakpoint
ALTER TABLE `warehouses` ADD `restored_at` timestamp;--> statement-breakpoint
ALTER TABLE `warehouses` ADD `restored_by` varchar(255);--> statement-breakpoint
ALTER TABLE `promotions` ADD `deleted_at` timestamp;--> statement-breakpoint
ALTER TABLE `promotions` ADD `deleted_by` varchar(255);--> statement-breakpoint
ALTER TABLE `promotions` ADD `restored_at` timestamp;--> statement-breakpoint
ALTER TABLE `promotions` ADD `restored_by` varchar(255);--> statement-breakpoint
ALTER TABLE `brands` ADD `deleted_at` timestamp;--> statement-breakpoint
ALTER TABLE `brands` ADD `deleted_by` varchar(255);--> statement-breakpoint
ALTER TABLE `brands` ADD `restored_at` timestamp;--> statement-breakpoint
ALTER TABLE `brands` ADD `restored_by` varchar(255);--> statement-breakpoint
ALTER TABLE `categories` ADD `deleted_at` timestamp;--> statement-breakpoint
ALTER TABLE `categories` ADD `deleted_by` varchar(255);--> statement-breakpoint
ALTER TABLE `categories` ADD `restored_at` timestamp;--> statement-breakpoint
ALTER TABLE `categories` ADD `restored_by` varchar(255);--> statement-breakpoint
ALTER TABLE `products` ADD `deleted_at` timestamp;--> statement-breakpoint
ALTER TABLE `products` ADD `deleted_by` varchar(255);--> statement-breakpoint
ALTER TABLE `products` ADD `restored_at` timestamp;--> statement-breakpoint
ALTER TABLE `products` ADD `restored_by` varchar(255);--> statement-breakpoint
ALTER TABLE `product_properties` ADD `deleted_at` timestamp;--> statement-breakpoint
ALTER TABLE `product_properties` ADD `deleted_by` varchar(255);--> statement-breakpoint
ALTER TABLE `product_properties` ADD `restored_at` timestamp;--> statement-breakpoint
ALTER TABLE `product_properties` ADD `restored_by` varchar(255);--> statement-breakpoint
ALTER TABLE `product_skus` ADD `deleted_at` timestamp;--> statement-breakpoint
ALTER TABLE `product_skus` ADD `deleted_by` varchar(255);--> statement-breakpoint
ALTER TABLE `product_skus` ADD `restored_at` timestamp;--> statement-breakpoint
ALTER TABLE `product_skus` ADD `restored_by` varchar(255);--> statement-breakpoint
ALTER TABLE `property_values` ADD `deleted_at` timestamp;--> statement-breakpoint
ALTER TABLE `property_values` ADD `deleted_by` varchar(255);--> statement-breakpoint
ALTER TABLE `property_values` ADD `restored_at` timestamp;--> statement-breakpoint
ALTER TABLE `property_values` ADD `restored_by` varchar(255);--> statement-breakpoint
ALTER TABLE `product_reviews` ADD `deleted_at` timestamp;--> statement-breakpoint
ALTER TABLE `product_reviews` ADD `deleted_by` varchar(255);--> statement-breakpoint
ALTER TABLE `product_reviews` ADD `restored_at` timestamp;--> statement-breakpoint
ALTER TABLE `product_reviews` ADD `restored_by` varchar(255);--> statement-breakpoint
CREATE INDEX `invoices_deleted_idx` ON `invoices` (`deleted_at`);--> statement-breakpoint
CREATE INDEX `campaigns_deleted_idx` ON `campaigns` (`deleted_at`);--> statement-breakpoint
CREATE INDEX `feature_flags_deleted_idx` ON `feature_flags` (`deleted_at`);--> statement-breakpoint
CREATE INDEX `warehouses_deleted_idx` ON `warehouses` (`deleted_at`);--> statement-breakpoint
CREATE INDEX `promotions_deleted_idx` ON `promotions` (`deleted_at`);--> statement-breakpoint
CREATE INDEX `brands_deleted_idx` ON `brands` (`deleted_at`);--> statement-breakpoint
CREATE INDEX `categories_deleted_idx` ON `categories` (`deleted_at`);--> statement-breakpoint
CREATE INDEX `products_deleted_idx` ON `products` (`deleted_at`);--> statement-breakpoint
CREATE INDEX `product_properties_deleted_idx` ON `product_properties` (`deleted_at`);--> statement-breakpoint
CREATE INDEX `product_skus_deleted_idx` ON `product_skus` (`deleted_at`);--> statement-breakpoint
CREATE INDEX `property_values_deleted_idx` ON `property_values` (`deleted_at`);--> statement-breakpoint
CREATE INDEX `product_reviews_deleted_idx` ON `product_reviews` (`deleted_at`);