export const PERMISSIONS = {
  users_read: "users:read",
  users_write: "users:write",
  roles_manage: "roles:manage",
  audit_read: "audit:read",
  orders_read: "orders:read",
  orders_write: "orders:write",
  products_read: "products:read",
  products_write: "products:write",
  delivery_manage: "delivery:manage",
  storefront_account: "storefront:account",
  brands_read: "brands:read",
  brands_write: "brands:write",
  categories_read: "categories:read",
  categories_write: "categories:write",
  preorders_read: "preorders:read",
  preorders_write: "preorders:write",
  inventory_read: "inventory:read",
  inventory_write: "inventory:write",
  inventory_forecast_read: "inventory:forecast:read",
  inventory_forecast_write: "inventory:forecast:write",
  reviews_read: "reviews:read",
  reviews_moderate: "reviews:moderate",
  promotions_read: "promotions:read",
  promotions_write: "promotions:write",
  analytics_read: "analytics:read",
  customers_read: "customers:read",
  campaigns_read: "campaigns:read",
  campaigns_write: "campaigns:write",
  invoices_read: "invoices:read",
  invoices_write: "invoices:write",
  shipping_read: "shipping:read",
  shipping_write: "shipping:write",
  settings_read: "settings:read",
  settings_write: "settings:write",
  // Operations workflow permissions
  escalations_read: "escalations:read",
  escalations_write: "escalations:write",
  holds_read: "holds:read",
  holds_write: "holds:write",
  cancellations_read: "cancellations:read",
  cancellations_write: "cancellations:write",
  follow_ups_read: "follow_ups:read",
  follow_ups_write: "follow_ups:write",
  support_cases_read: "support_cases:read",
  support_cases_write: "support_cases:write",
  warranty_read: "warranty:read",
  warranty_write: "warranty:write",
  payment_verification_read: "payment_verification:read",
  payment_verification_write: "payment_verification:write",
  refund_read: "refund:read",
  refund_write: "refund:write",
  tasks_read: "tasks:read",
  tasks_write: "tasks:write",
  notifications_read: "notifications:read",
} as const;

export type PermissionName = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];

export const ROLE_PERMISSION_MAP: Record<string, PermissionName[]> = {
  admin: Object.values(PERMISSIONS),
  moderator: [
    PERMISSIONS.users_read,
    PERMISSIONS.orders_read,
    PERMISSIONS.orders_write,
    PERMISSIONS.products_read,
    PERMISSIONS.products_write,
    PERMISSIONS.audit_read,
    PERMISSIONS.brands_read,
    PERMISSIONS.categories_read,
    PERMISSIONS.categories_write,
    PERMISSIONS.inventory_read,
    PERMISSIONS.inventory_write,
    PERMISSIONS.reviews_read,
    PERMISSIONS.reviews_moderate,
    PERMISSIONS.analytics_read,
    PERMISSIONS.customers_read,
    PERMISSIONS.campaigns_read,
    PERMISSIONS.campaigns_write,
    PERMISSIONS.invoices_read,
    PERMISSIONS.shipping_read,
    PERMISSIONS.settings_read,
    PERMISSIONS.escalations_read,
    PERMISSIONS.escalations_write,
    PERMISSIONS.holds_read,
    PERMISSIONS.holds_write,
    PERMISSIONS.cancellations_read,
    PERMISSIONS.cancellations_write,
    PERMISSIONS.follow_ups_read,
    PERMISSIONS.follow_ups_write,
    PERMISSIONS.support_cases_read,
    PERMISSIONS.support_cases_write,
    PERMISSIONS.warranty_read,
    PERMISSIONS.warranty_write,
    PERMISSIONS.tasks_read,
    PERMISSIONS.tasks_write,
    PERMISSIONS.notifications_read,
  ],
  operator: [
    PERMISSIONS.orders_read,
    PERMISSIONS.orders_write,
    PERMISSIONS.products_read,
    PERMISSIONS.products_write,
    PERMISSIONS.brands_read,
    PERMISSIONS.categories_read,
    PERMISSIONS.inventory_read,
    PERMISSIONS.inventory_write,
    PERMISSIONS.shipping_read,
    PERMISSIONS.shipping_write,
    PERMISSIONS.escalations_read,
    PERMISSIONS.escalations_write,
    PERMISSIONS.holds_read,
    PERMISSIONS.holds_write,
    PERMISSIONS.cancellations_read,
    PERMISSIONS.cancellations_write,
    PERMISSIONS.follow_ups_read,
    PERMISSIONS.follow_ups_write,
    PERMISSIONS.support_cases_read,
    PERMISSIONS.support_cases_write,
    PERMISSIONS.tasks_read,
    PERMISSIONS.tasks_write,
    PERMISSIONS.notifications_read,
  ],
  delivery_person: [
    PERMISSIONS.delivery_manage,
    PERMISSIONS.orders_read,
    PERMISSIONS.shipping_read,
    PERMISSIONS.notifications_read,
  ],
  customer: [PERMISSIONS.storefront_account],
};
